import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header.jsx";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Header/>

          <main className="min-h-screen pt-20">{children}</main> 
          <Toaster richColors />

          <footer className="bg-blue-50 py-12">
            <div className="container mx-auto px-4 text-center text-gray-500"><p>This is footer</p></div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
